C229_G2/Models/Team.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace C229_G2.Models
{
    public class Team
    {
        public int TeamID { get; set; }
        [Required]
        public string Name { get; set; }
        public Club Club { get; set; }
        public ICollection<TeamPlayer> Players { get; set; }

    }
}

C229_G2/Models/ViewModels/TeamViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace C229_G2.Models.ViewModels
{
    public class TeamViewModel
    {
        public Team Team { get; set; }
        public IEnumerable<Club> Clubs { get; set; }
        public int SelectedClubID { get; set; }
    }
}

C229_G2/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using C229_G2.Models;
using C229_G2.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace C229_G2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TeamController : Controller
    {
        private ITeamRepository teamRepository;
        private IClubRepository clubRepository;

        public TeamController(ITeamRepository teamRepository, IClubRepository clubRepository)
        {
            this.teamRepository = teamRepository;
            this.clubRepository = clubRepository;
        }

        [AllowAnonymous]
        public IActionResult List() => View(teamRepository.Teams);

        public IActionResult Edit(int teamID)
        {
            Team team = teamRepository.Teams.FirstOrDefault(c => c.TeamID == teamID);

            return View("Edit",
                 new TeamViewModel
                 {
                     Team = team,
                     Clubs = clubRepository.Clubs,
                     SelectedClubID = team.Club.ClubID
                 });
        }

        [HttpPost]
        public IActionResult Edit(TeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Team.Club = clubRepository.Clubs.FirstOrDefault(c => c.ClubID==model.SelectedClubID);
                teamRepository.Save(model.Team);
                TempData["message"] = $"{model.Team.Name} has been saved.";
                return RedirectToAction("List");
            }
            else
            {
                model.Clubs = clubRepository.Clubs;
                return View(model);
            }
        }

        public IActionResult Create() => 
            View("Edit", 
                 new TeamViewModel
                 {
                     Team = new Team(),
                     Clubs = clubRepository.Clubs
                 });
        public IActionResult Delete()
        {
            return RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult Delete(int teamId)
        {
            Team team = teamRepository.Delete(teamId);
            if (team != null)
            {
                TempData["message"] = $"{team.Name} has been deleted";
            }
            return RedirectToAction("List");
        }

        [AllowAnonymous]
        public IActionResult Detail(int teamID)
        {
            return View(new TeamViewModel()
            {
                Team = teamRepository.Teams.FirstOrDefault(c => c.TeamID == teamID),
                Clubs = clubRepository.Clubs.ToList()
            });
        }

    }
}

C229_G2/Views/Team/Detail.cshtml
@model TeamViewModel

<h2>Team Details</h2>

<div class="card bg-light">
    <div class="card-body">
        <h5 class="card-title">@Model.Team.Name</h5>
        <p class="card-text text-muted">
            @Model.Team.Club.Name
            <span class="float-right mr-3">Email: @Model.Team.Club.Email</span>
            <span class="float-right mr-3">Phone: @Model.Team.Club.Phone</span>
        </p>
    </div>
</div>

@if (Model.Team.Players.Count > 0)
{
    <h5 class="mt-3">Players</h5>

    <table class="table table-sm table-striped table-bordered mt-4">
        <thead>
            <tr>
                <th>TeamPlayer Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Position</th>
            </tr>
        </thead>
        <tbody>
            @foreach (TeamPlayer player in Model?.Team?.Players)
            {
                <tr>
                    <td>@player.TeamPlayerID</td>
                    <td>@player.Player.FirstName</td>
                    <td>@player.Player.LastName</td>
                    <td>@player.Player.Age</td>
                    <td>@player.Player.Phone</td>
                    <td>@player.Player.Email</td>
                    <td>@player.Position</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="text-center m-5">The team has no registered players</div>
}

<div class="text-center">
    <a asp-action="Create" asp-controller="TeamPlayer" asp-route-teamId="@Model.Team.TeamID" class="btn btn-primary">Add Player</a>
    <a asp-action="List" asp-controller="Team" class="btn btn-secondary">Back</a>
</div>

C229_G2/Views/Team/Edit.cshtml
@model TeamViewModel

<h2>Team</h2>
<p>Please enter the team  details.</p>

<form asp-action="Edit" asp-controller="Team" method="post">

    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="Team.TeamID" />
    <div class="form-group">
        <label asp-for="Team.Name"></label>
        <input asp-for="Team.Name" class="form-control" />
        <span asp-validation-for="Team.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Team.Club">Club:</label>
        <select asp-for="SelectedClubID" class="form-control"
                asp-items="@(new SelectList(Model.Clubs,"ClubID","Name"))">
            <option>Please select one</option>
        </select>
        <span asp-validation-for="Team.Club" class="text-danger"></span>
    </div>

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="List" asp-controller="Team" class="btn btn-secondary">Cancel</a>
    </div>

</form>

C229_G2/Views/Team/List.cshtml
@model IEnumerable<Team>

<h2>Team List</h2>
<table class="table table-sm table-striped table-bordered mt-4">
    <thead>
        <tr>
            <th>Team ID</th>
            <th>Name</th>
            <th>Club</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Team team in Model)
        {
            <tr>
                <td>@team.TeamID</td>
                <td>@team.Name</td>
                <td>@team.Club.Name</td>
                <td class="text-center">
                    <form asp-action="Delete" method="post">
                        <a asp-action="Edit" class="btn btn-sm btn-warning"
                           asp-route-teamId="@team.TeamID">
                            Edit
                        </a>
                        <input type="hidden" name="TeamID" value="@team.TeamID" />
                        <button type="submit" class="btn btn-danger btn-sm">
                            Delete
                        </button>
                        <a asp-action="Detail" class="btn btn-sm btn-secondary"
                           asp-route-teamId="@team.TeamID">
                            Details
                        </a>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="text-center">
    <a asp-action="Create" asp-controller="Team" class="btn btn-primary">Add Team</a>
</div>