C229_G2/Models/Club.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace C229_G2.Models
{
    public class Club
    {
        public int ClubID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        public ICollection<Player> Players { get; set; }

    }
}

C229_G2/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using C229_G2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace C229_G2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ClubController : Controller
    {
        private IClubRepository repository;

        public ClubController(IClubRepository repo)
        {
            repository = repo;
        }

        [AllowAnonymous]
        public IActionResult List() => View(repository.Clubs);

        public IActionResult Edit(int clubID)
        {
            return View(repository.Clubs.FirstOrDefault(c=>c.ClubID==clubID));
        }

        [HttpPost]
        public IActionResult Edit(Club club)
        {
            if (ModelState.IsValid)
            {
                repository.Save(club);
                TempData["message"] = $"{club.Name} has been saved.";
                return RedirectToAction("List");
            }
            else
            {
                return View(club);
            }
        }

        public IActionResult Create() => View("Edit", new Club());

        public IActionResult Delete()
        {

            return RedirectToAction("List");
        }
        [HttpPost]
        public IActionResult Delete(int clubId)
        {
            Club club = repository.Clubs.FirstOrDefault(c=>c.ClubID==clubId);
            try
            {
                club = repository.Delete(club.ClubID);
                TempData["message"] = $"{club.Name} has been deleted";

            }
            catch (Exception)
            {
                TempData["messageError"] = $"{club.Name} cannot be deleted because there are teams associated.";
            }
            return RedirectToAction("List");
        }

        [AllowAnonymous]
        public IActionResult Detail(int clubID)
        {
            return View(repository.Clubs.FirstOrDefault(c => c.ClubID == clubID));
        }

    }
}

C229_G2/Views/Club/Detail.cshtml
@model Club

<h2>Club Details</h2>

<div class="card bg-light">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text text-muted">
            @Model.Address
            <span class="float-right mr-3">Email: @Model.Email</span>
            <span class="float-right mr-3">Phone: @Model.Phone</span>
        </p>
    </div>
</div>

@if (Model.Players.Count > 0)
{
    <h5 class="mt-3">Players</h5>

    <table class="table table-sm table-striped table-bordered mt-4">
        <thead>
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th>Phone</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Player player in Model?.Players)
            {
                <tr>
                    <td>@player.PlayerID</td>
                    <td>@player.FirstName</td>
                    <td>@player.LastName</td>
                    <td>@player.Age</td>
                    <td>@player.Phone</td>
                    <td>@player.Email</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="text-center m-5">The club has no registered players</div>
}

<div class="text-center">
    <a asp-action="Create" asp-controller="Player" asp-route-clubId="@Model.ClubID" class="btn btn-primary">Add Player</a>
    <a asp-action="List"   asp-controller="Club" class="btn btn-secondary">Back</a>
</div>

C229_G2/Views/Club/Edit.cshtml

<h2>Club</h2>
<p>Please enter the club  details.</p>

<form asp-action="Edit" asp-controller="Club" method="post">

    @await Html.PartialAsync("_ClubPartialForm")

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="List" asp-controller="Club" class="btn btn-secondary">Cancel</a>
    </div>

</form>

C229_G2/Views/Club/List.cshtml
@model IEnumerable<Club>

<h2>Clubs List</h2>
<table class="table table-sm table-striped table-bordered mt-4">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Email</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Club club in Model)
        {
            <tr>
                <td>@club.ClubID</td>
                <td>@club.Name</td>
                <td>@club.Address</td>
                <td>@club.Phone</td>
                <td>@club.Email</td>
                <td class="text-center">
                    <form asp-action="Delete" method="post">
                        <a asp-action="Edit" class="btn btn-sm btn-warning"
                            asp-route-clubId="@club.ClubID">
                            Edit
                        </a>
                        <input type="hidden" name="ClubID" value="@club.ClubID" />
                        <button type="submit" class="btn btn-danger btn-sm">
                            Delete
                        </button>
                        <a asp-action="Detail" class="btn btn-sm btn-secondary"
                            asp-route-clubId="@club.ClubID">
                            Details
                        </a>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="text-center">
    <a asp-action="Create" asp-controller="Club" class="btn btn-primary">Add Club</a>
</div>