C229_G2/Models/MatchPlayer.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace C229_G2.Models
{
    public class MatchPlayer
    {
        public int MatchPlayerID { get; set; }
        public Match Match { get; set; }
        public TeamPlayer TeamPlayer { get; set; }

        [Range(0, 1000)]
        public int RedCards { get; set; }
        [Range(0, 1000)]
        public int YellowCards { get; set; }
        [Range(0, 1000)]
        public int Goals { get; set; }
    }

}

C229_G2/Models/ViewModels/MatchPlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace C229_G2.Models.ViewModels
{
    public class MatchPlayerViewModel
    {
        public MatchPlayer MatchPlayer { get; set; }
        public ICollection<TeamPlayer> TeamPlayers { get; set; }
        public int SelectedTeamPlayerID { get; set; }
        public int TeamID { get; set; }

    }
}

C229_G2/Controllers/MatchPlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using C229_G2.Models;
using C229_G2.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace C229_G2.Controllers
{
    [Authorize(Roles = "Admin,General")]
    public class MatchPlayerController : Controller
    {
        private IMatchRepository matchRepository;
        private ITeamRepository teamRepository;

        public MatchPlayerController(IMatchRepository matchRepository, ITeamRepository teamRepository)
        {
            this.matchRepository = matchRepository;
            this.teamRepository = teamRepository;
        }

        public IActionResult Edit(int matchID, int matchPlayerID)
        {
            MatchPlayer matchPlayer = matchRepository.Matches.FirstOrDefault(m => m.MatchID == matchID)
                    .MatchPlayers.FirstOrDefault(mp=>mp.MatchPlayerID==matchPlayerID);
            Team team = teamRepository.Teams.FirstOrDefault(t => t.TeamID == matchPlayer.TeamPlayer.Team.TeamID);
            MatchPlayerViewModel modelView = new MatchPlayerViewModel
            {
                MatchPlayer = matchPlayer,
                TeamPlayers = team.Players.ToList(),
                TeamID = team.TeamID,
                SelectedTeamPlayerID = matchPlayer.TeamPlayer.TeamPlayerID
            };
            return View(modelView);
        }

        [HttpPost]
        public IActionResult Edit(MatchPlayerViewModel model, int matchId, int teamId)
        {
            Match match = matchRepository.Matches.FirstOrDefault(c => c.MatchID == matchId);
            Team team = teamRepository.Teams.FirstOrDefault(t => t.TeamID == teamId);
            if (ModelState.IsValid)
            {
                model.MatchPlayer.Match = match;
                model.MatchPlayer.TeamPlayer = team.Players.FirstOrDefault(tp => tp.TeamPlayerID==model.SelectedTeamPlayerID);

                if (model.MatchPlayer.MatchPlayerID == 0) 
                {
                    match.MatchPlayers.Add(model.MatchPlayer);
                }
                else
                {
                    MatchPlayer matchPlayerDb = match.MatchPlayers.First(mp => mp.MatchPlayerID == model.MatchPlayer.MatchPlayerID);
                    matchPlayerDb.TeamPlayer = model.MatchPlayer.TeamPlayer;
                    matchPlayerDb.Goals = model.MatchPlayer.Goals;
                    matchPlayerDb.YellowCards = model.MatchPlayer.YellowCards;
                    matchPlayerDb.RedCards = model.MatchPlayer.RedCards;
                }

                calculateGoals(match);

                matchRepository.Save(match);
                TempData["message"] = $"An event has been created to {model.MatchPlayer.TeamPlayer.Player.FullName} for the match.";
                return RedirectToAction("Detail", "Match", new { matchId });
            }
            else
            {
                MatchPlayerViewModel modelView = new MatchPlayerViewModel
                {
                    MatchPlayer = new MatchPlayer { Match = match },
                    TeamPlayers = team.Players.ToList(),
                    TeamID = team.TeamID
                };
                return View(modelView);
            }
        }

        private void calculateGoals(Match match)
        {
            match.HomeGoals = match.MatchPlayers.OfType<MatchPlayer>()
                                                .Where(mp => mp.TeamPlayer.Team == match.HomeTeam)
                                                .Sum(mp => mp.Goals);
            match.AwayGoals = match.MatchPlayers.OfType<MatchPlayer>()
                                                .Where(mp => mp.TeamPlayer.Team == match.AwayTeam)
                                                .Sum(mp => mp.Goals);
        }

        public IActionResult Delete(MatchPlayerViewModel model, int matchId, int matchPlayerId)
        {
            Match match = matchRepository.Matches.FirstOrDefault(c => c.MatchID == matchId);
            if (ModelState.IsValid)
            {
                MatchPlayer matchPlayer = match.MatchPlayers.FirstOrDefault(mp => mp.MatchPlayerID == matchPlayerId);
                match.MatchPlayers.Remove(matchPlayer);
                calculateGoals(match);
                matchRepository.Save(match);
                TempData["message"] = $"An event has been removed for {matchPlayer.TeamPlayer.Player.FullName}.";
            }
            return RedirectToAction("Detail", "Match", new { matchId });
        }

        public IActionResult Create(int matchId, int teamId)
        {
            Match match = matchRepository.Matches.FirstOrDefault(c => c.MatchID == matchId);
            Team team = teamRepository.Teams.FirstOrDefault(t => t.TeamID == teamId);

            MatchPlayerViewModel model = new MatchPlayerViewModel
            {
                MatchPlayer = new MatchPlayer { Match = match },
                TeamPlayers = team.Players.ToList(),
                TeamID = team.TeamID
            };
            return View("Edit", model);
        }

    }
}

C229_G2/Views/MatchPlayer/Edit.cshtml
@model MatchPlayerViewModel

<h2>Register Event for a Player</h2>
<p>Please select a player:</p>

<div class="card bg-light">
    <div class="card-body">
        <h5 class="card-title">@Model.MatchPlayer.Match.HomeTeam.Name vs @Model.MatchPlayer.Match.AwayTeam.Name</h5>
        <p class="card-text text-muted">
            @Model.MatchPlayer.Match.Date
            <span class="float-right mr-3">Location: @Model.MatchPlayer.Match.Location</span>
            <span class="float-right mr-3">Referee: @Model.MatchPlayer.Match.Referee</span>
        </p>
    </div>
</div>

<form asp-action="Edit" asp-controller="MatchPlayer" method="post"
      asp-route-matchId="@Model.MatchPlayer.Match.MatchID">

    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="MatchPlayer.MatchPlayerID" />
    <input type="hidden" asp-for="TeamID" />
    <div class="form-group">
        <label asp-for="MatchPlayer.MatchPlayerID">Player:</label>
        <select asp-for="SelectedTeamPlayerID" class="form-control"
                asp-items="@(new SelectList(Model.TeamPlayers,"TeamPlayerID","Player"))">
            <option>Please select one</option>
        </select>
        <span asp-validation-for="MatchPlayer.MatchPlayerID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="MatchPlayer.Goals"></label>
        <input asp-for="MatchPlayer.Goals" class="form-control" />
        <span asp-validation-for="MatchPlayer.Goals" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="MatchPlayer.YellowCards"></label>
        <input asp-for="MatchPlayer.YellowCards" class="form-control" />
        <span asp-validation-for="MatchPlayer.YellowCards" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="MatchPlayer.RedCards"></label>
        <input asp-for="MatchPlayer.RedCards" class="form-control" />
        <span asp-validation-for="MatchPlayer.RedCards" class="text-danger"></span>
    </div>

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Detail" asp-controller="Match"
           asp-route-matchId="@Model.MatchPlayer.Match.MatchID"
           class="btn btn-secondary">Cancel</a>
    </div>

</form>