C229_G2/Models/TeamPlayer.cs
using System.ComponentModel.DataAnnotations;

namespace C229_G2.Models
{
    public class TeamPlayer
    {
        public int TeamPlayerID { get; set; }
        [Required]
        public Team Team { get; set; }
        public Player Player { get; set; }
        [Required]
        public string Position { get; set; }
    }
}

C229_G2/Models/ViewModels/TeamPlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace C229_G2.Models.ViewModels
{
    public class TeamPlayerViewModel
    {
        public TeamPlayer TeamPlayer { get; set; }
        public ICollection<Player> Players { get; set; }
        public int SelectedTeamPlayerID { get; set; }
    }
}

C229_G2/Controllers/TeamPlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using C229_G2.Models;
using C229_G2.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace C229_G2.Controllers
{
    [Authorize(Roles = "Admin,General")]
    public class TeamPlayerController : Controller
    {
        private ITeamRepository teamRepository;
        private IPlayerRepository playerRepository;

        public TeamPlayerController(ITeamRepository teamRepository, IPlayerRepository playerRepository)
        {
            this.teamRepository = teamRepository;
            this.playerRepository = playerRepository;
        }

        public IActionResult Edit(TeamPlayerViewModel model, int teamId)
        {
            Team team = teamRepository.Teams.FirstOrDefault(c => c.TeamID == teamId);
            if (ModelState.IsValid)
            {
                model.TeamPlayer.Team = team;
                model.TeamPlayer.Player = playerRepository.Players.FirstOrDefault(p => p.PlayerID==model.SelectedTeamPlayerID);
                team.Players.Add(model.TeamPlayer);
                teamRepository.Save(team);
                TempData["message"] = $"{model.TeamPlayer.Player.FirstName} has been assigned to the team.";
                return RedirectToAction("Detail", "Team", new { teamId });
            }
            else
            {
                TeamPlayerViewModel modelView = new TeamPlayerViewModel
                {
                    TeamPlayer = new TeamPlayer { Team = team },
                    Players = playerRepository.Players.Where(p => p.Club == team.Club).ToList()
                };
                return View(modelView);
            }
        }

        public IActionResult Create(int teamId)
        {
            Team team = teamRepository.Teams.FirstOrDefault(c => c.TeamID == teamId);
            TeamPlayerViewModel model = new TeamPlayerViewModel
            {
                TeamPlayer = new TeamPlayer { Team = team },
                Players = playerRepository.Players.Where(p => p.Club == team.Club).ToList()
            };
            return View("Edit", model);
        }

    }
}

C229_G2/Views/TeamPlayer/Edit.cshtml
@model TeamPlayerViewModel

<h2>Assign Players</h2>
<p>Please Check Combobox to assign player:</p>

<div class="card bg-light">
    <div class="card-body">
        <h5 class="card-title">@Model.TeamPlayer.Team.Name</h5>
        <p class="card-text text-muted">
            @Model.TeamPlayer.Team.Club.Name
            <span class="float-right mr-3">Email: @Model.TeamPlayer.Team.Club.Email</span>
            <span class="float-right mr-3">Phone: @Model.TeamPlayer.Team.Club.Phone</span>
        </p>
    </div>
</div>

<form asp-action="Edit" asp-controller="TeamPlayer" asp-route-teamId="@Model.TeamPlayer.Team.TeamID" method="post">

    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="TeamPlayer.TeamPlayerID" />
    <input type="hidden" asp-for="TeamPlayer.Team.TeamID" />
    <input type="hidden" asp-for="TeamPlayer.Team.Name" />
    <div class="form-group">
        <label asp-for="TeamPlayer.Player">Player:</label>
        <select asp-for="SelectedTeamPlayerID" class="form-control"
                asp-items="@(new SelectList(Model.Players,"PlayerID","FullName"))">
            <option>Please select one</option>
        </select>
        <span asp-validation-for="TeamPlayer.Player" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TeamPlayer.Position">Position:</label>
        <select asp-for="TeamPlayer.Position" class="form-control">
            <option value="">Please select...</option>
            <option value="Goalkeeper">Goalkeeper</option>
            <option value="Defender">Defender</option>
            <option value="Midfielder">Midfielder</option>
            <option value="Forward">Forward</option>
        </select>
    </div>

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Detail" asp-controller="Team" asp-route-teamId="@Model.TeamPlayer.Team.TeamID"
           class="btn btn-secondary">Cancel</a>
    </div>

</form>